### ISSUE TITLE
Player gets stuck, when the areas are changed during flight.

### ISSUE THREAD

**Issue by ghost** [minetest-mods/towercrane#3]
When I gave an area to another player during flight, I got stuck in the area, because the old position saved by the crane isn't belonging to me anymore. That's why the crane tries to teleport me to the same point. I tried to log out to solve the problem. But this crashed the Server.

**Comment by joe7575** [comment]
Thanks for the report alxki, I will fix that ASAP.

**Comment by joe7575** [comment]
I can reproduce it but I have no idea what happens. I sometimes (each ~5th time)  get 'Speicherzugriffsfehler' when the player on the crane leaves the game:
```
2018-04-12 19:41:01: ACTION[Server]: t62 leaves game. List of players: JoSto 
Speicherzugriffsfehler (Speicherabzug geschrieben)
2018-04-12 20:23:52: ACTION[Server]: t62 leaves game. List of players: 
Speicherzugriffsfehler (Speicherabzug geschrieben)
2018-04-12 20:31:38: ACTION[Server]: t62 leaves game. List of players: 
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

**Comment by joe7575** [comment]
I have located the critical line if code. After I added the print function:
```
	local last_pos = minetest.string_to_pos(meta:get_string("last_known_pos"))
	if last_pos and player and player:is_player() then
		print(player:get_player_name())
		print("1", minetest.pos_to_string(last_pos))
		player:setpos(last_pos)	
		print("2")
	end
```
I get this:
```
2018-04-12 20:59:17: ACTION[Server]: t62 leaves game. List of players: 
t62
1	(-237,16,-192)
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

It seems that 'player:setpos(last_pos)' crashes even if 'player' and 'last_pos' is valid

**Comment by joe7575** [comment]
Ok, I fixed it.
Now I maintain my own list of players online, which could be checked before calling `player:setpos(last_pos)	`
